### PR TITLE
Change remove_provinces

### PR DESCRIPTION
**Pull request by gasilva**
Changed remove_provinces to sumCases_provinces; changed ODE solver from solve_ivp to odeint, because it is a compiled FORTRAN routine, faster than Python interpreted; change little things in plotting

### CODE REVIEW

**Comment by Lewuathe** [comment]
@gasilva I cannot see any difference in the PR. Could you check it?

**Comment by gasilva** [comment]
> @gasilva I cannot see any difference in the PR. Could you check it?

see the fd39930

image

**Comment by gasilva** [comment]
6567b08 was cancelled because it duplicated 
fd39930

**Comment by gasilva** [comment]
I could not open another pull request so I did it here. See only the remove_provinces changes.

**Pull request closed without merging**
