### PR TITLE
deleted remove_provinces

### PR DESCRIPTION
**Pull request by gasilva**
A new try for pulling the changes
Please see files changed in the menu above.

image

### CODE REVIEW

**Comment by bolinches** [comment]
Hi I tried to run the pull request and does not generate the same graphs for me. taking a quick look into the code it seems there are a lot of changes on the SIR part. M guess is it would be easier to break those on different requests so if we need to pull back or test we can see what is to be changed

I like ht enew look of the graph with titles

**Comment by gasilva** [comment]
OK I will try

**Comment by gasilva** [comment]
any news? @bolinches

**Comment by Lewuathe** [comment]
Hi @gasilva. Thank you for sending the PR. But there seems to be another [PR](https://github.com/Lewuathe/COVID19-SIR/pull/19). Which one is the correct one? Could you close the unnecessary one?

**Comment by gasilva** [comment]
Closed.
Guilherme A. Lima da Silva,Dr.  





On Sat, Apr 4, 2020 10:02 AM, Kai Sasaki notifications@github.com  wrote:


Hi @gasilva. Thank you for sending the PR. But there seems to be another PR.
Which one is the correct one? Could you close the unnecessary one?

**Comment by itsisthatis** [comment]
@Lewuathe can I get the code for generating the graph

**Comment by gasilva** [comment]
> @Lewuathe can I get the code for generating the graph

Yes. Sure. I think you asked to have one modification at time. I am just waiting.

**Comment by itsisthatis** [comment]
Thanks btw! I figured out the code by making slight modifications. The code
is now successfully generating the graph.

**Comment by Lewuathe** [comment]
@gasilva Thanks for the PR. I confirmed it works properly too. LGTM.

@itsisthatis Thanks for checking in advance!

**Pull request merged**
